name: Veracode Scan

on: [ push, pull_request ]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: veracode/pipeline-scan:latest

    steps:
      - name: Checkout Repoisitory
        uses: actions/checkout@v4

      - name: Veracode CLI Autopacker
        run: |
          /home/gvg/tools/veracode package --source . --trust yes --output /tmp/veracode.zip
          ls

